name: flutter_dunimarket
description: "Duni Market, Flutter based E-commerce Application."
publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
 flutter:
   sdk: flutter
 bloc: ^8.1.4
 dio: ^5.5.0+1
 get_it: ^7.7.0
 go_router: ^14.2.0
 flutter_bloc: ^8.1.6
 shared_preferences: ^2.2.3
 equatable: ^2.0.5
 google_fonts: ^6.2.1
 icons_plus: ^5.0.0
 firebase_core: ^3.2.0
 cloud_firestore: ^5.1.0
 firebase_auth: ^5.1.2
 flutter_secure_storage: ^9.2.2
 lottie: ^3.1.2
 flutter_spinkit: ^5.2.1
 pinput: ^5.0.0
 awesome_snackbar_content: ^0.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/intro/
    - assets/Images/
    - assets/animation/

